language      : php
php           : [5.6, 7.0, 7.1]
cache         : { directories : [$COMPOSER_CACHE_DIR, $HOME/.composer/cache, vendor] }
install       : composer update --no-interaction --prefer-dist
notifications :
    email : false

stages :
    - test
    - lint

env :
    - TESTBENCH_VERSION=3.2.* LARAVEL_VERSION=5.2.*
    - TESTBENCH_VERSION=3.3.* LARAVEL_VERSION=5.3.*
    - TESTBENCH_VERSION=3.4.* LARAVEL_VERSION=5.4.*
    - TESTBENCH_VERSION=3.5.* LARAVEL_VERSION=5.5.*
    - TESTBENCH_VERSION=3.6.*@dev LARAVEL_VERSION=5.6.*

matrix :
    exclude :
        - php : 5.6
          env : TESTBENCH_VERSION=3.5.* LARAVEL_VERSION=5.5.*
        - php : 5.6
          env : TESTBENCH_VERSION=3.6.*@dev LARAVEL_VERSION=5.6.*
        - php : 7.0
          env : TESTBENCH_VERSION=3.6.*@dev LARAVEL_VERSION=5.6.*

script :
    - vendor/bin/phpunit

before_install :
    - composer global require hirak/prestissimo --update-no-dev
    - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update --prefer-dist
    - composer require "orchestra/testbench-browser-kit:${TESTBENCH_VERSION}" --no-update --prefer-dist

jobs :
    include :
        - stage : lint
          php   : 7.1
          env   : TESTBENCH_VERSION=3.6.*@dev LARAVEL_VERSION=5.6.*
          before_install :
            - composer global require hirak/prestissimo --update-no-dev
            - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update --prefer-dist
            - composer require "orchestra/testbench-browser-kit:${TESTBENCH_VERSION}" --no-update --prefer-dist
            - composer require phpmd/phpmd --no-update --prefer-dist
            - composer require phpstan/phpstan --no-update --prefer-dist
            - composer require friendsofphp/php-cs-fixer --no-update --prefer-dist
          script :
              - vendor/bin/phpmd src text phpmd.xml
              - vendor/bin/phpmd tests text phpmd.xml
              - vendor/bin/phpstan analyse --autoload-file=_ide_helper.php --level 1 src
              - vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no
